-- Restaurant Atlas shared database schema
-- Run in the Supabase SQL editor. Safe to run more than once.

create extension if not exists citext;

create table if not exists public.atlas_members (
  id uuid primary key default gen_random_uuid(),
  email citext not null unique,
  role text not null default 'member' check (role in ('owner', 'member')),
  user_id uuid unique,
  invited_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurants (
  id text primary key,
  name text not null check (char_length(name) between 1 and 120),
  food numeric(3,1) check (food between 1 and 10),
  ambiance numeric(3,1) check (ambiance between 1 and 10),
  price numeric(3,1) check (price between 1 and 10),
  overall numeric(3,1) check (overall between 1 and 10),
  return_verdict text not null default '' check (return_verdict in ('', 'yes', 'maybe', 'no')),
  notes text not null default '' check (char_length(notes) <= 1500),
  dish text not null default '' check (char_length(dish) <= 160),
  created timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid,
  updated_by_email text,
  version integer not null default 1 check (version > 0)
);

create table if not exists public.restaurant_history (
  id bigint generated by default as identity primary key,
  restaurant_id text not null,
  action text not null check (action in ('created', 'updated', 'deleted')),
  snapshot jsonb not null,
  changed_by uuid,
  changed_by_email text,
  changed_at timestamptz not null default now()
);

alter table public.atlas_members enable row level security;
alter table public.restaurants enable row level security;
alter table public.restaurant_history enable row level security;

create or replace function public.is_atlas_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.atlas_members
    where lower(email::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.is_atlas_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.atlas_members
    where lower(email::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and role = 'owner'
  );
$$;

create or replace function public.claim_atlas_membership()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed_role text;
begin
  update public.atlas_members
  set user_id = auth.uid(), updated_at = now()
  where lower(email::text) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and (user_id is null or user_id = auth.uid())
  returning role into claimed_role;
  return claimed_role;
end;
$$;

create or replace function public.stamp_restaurant()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  new.updated_by_email = auth.jwt() ->> 'email';
  if tg_op = 'UPDATE' then
    new.version = old.version + 1;
  end if;
  return new;
end;
$$;

create or replace function public.record_restaurant_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.restaurant_history
      (restaurant_id, action, snapshot, changed_by, changed_by_email)
    values
      (old.id, 'deleted', to_jsonb(old), auth.uid(), auth.jwt() ->> 'email');
    return old;
  end if;

  insert into public.restaurant_history
    (restaurant_id, action, snapshot, changed_by, changed_by_email)
  values
    (new.id, case when tg_op = 'INSERT' then 'created' else 'updated' end,
     to_jsonb(new), auth.uid(), auth.jwt() ->> 'email');
  return new;
end;
$$;

create or replace function public.protect_last_owner()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' and old.role = 'owner' then
    if (select count(*) from public.atlas_members where role = 'owner' and id <> old.id) = 0 then
      raise exception 'Restaurant Atlas must always have an owner';
    end if;
    return old;
  end if;
  if tg_op = 'UPDATE' and old.role = 'owner' and new.role <> 'owner' then
    if (select count(*) from public.atlas_members where role = 'owner' and id <> old.id) = 0 then
      raise exception 'Restaurant Atlas must always have an owner';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists restaurants_stamp on public.restaurants;
create trigger restaurants_stamp
before insert or update on public.restaurants
for each row execute function public.stamp_restaurant();

drop trigger if exists restaurants_history on public.restaurants;
create trigger restaurants_history
after insert or update or delete on public.restaurants
for each row execute function public.record_restaurant_history();

drop trigger if exists members_protect_last_owner on public.atlas_members;
create trigger members_protect_last_owner
before update or delete on public.atlas_members
for each row execute function public.protect_last_owner();

drop policy if exists "members can read members" on public.atlas_members;
create policy "members can read members"
on public.atlas_members for select to authenticated
using (public.is_atlas_member());

drop policy if exists "owners can add members" on public.atlas_members;
create policy "owners can add members"
on public.atlas_members for insert to authenticated
with check (public.is_atlas_owner());

drop policy if exists "owners can update members" on public.atlas_members;
create policy "owners can update members"
on public.atlas_members for update to authenticated
using (public.is_atlas_owner()) with check (public.is_atlas_owner());

drop policy if exists "owners can remove members" on public.atlas_members;
create policy "owners can remove members"
on public.atlas_members for delete to authenticated
using (public.is_atlas_owner());

drop policy if exists "members can read restaurants" on public.restaurants;
create policy "members can read restaurants"
on public.restaurants for select to authenticated
using (public.is_atlas_member());

drop policy if exists "members can add restaurants" on public.restaurants;
create policy "members can add restaurants"
on public.restaurants for insert to authenticated
with check (public.is_atlas_member());

drop policy if exists "members can update restaurants" on public.restaurants;
create policy "members can update restaurants"
on public.restaurants for update to authenticated
using (public.is_atlas_member()) with check (public.is_atlas_member());

drop policy if exists "members can delete restaurants" on public.restaurants;
create policy "members can delete restaurants"
on public.restaurants for delete to authenticated
using (public.is_atlas_member());

drop policy if exists "members can read history" on public.restaurant_history;
create policy "members can read history"
on public.restaurant_history for select to authenticated
using (public.is_atlas_member());

revoke all on public.atlas_members, public.restaurants, public.restaurant_history from anon;
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.atlas_members to authenticated;
grant select, insert, update, delete on public.restaurants to authenticated;
grant select on public.restaurant_history to authenticated;
grant usage, select on sequence public.restaurant_history_id_seq to authenticated;
grant execute on function public.is_atlas_member() to authenticated;
grant execute on function public.is_atlas_owner() to authenticated;
grant execute on function public.claim_atlas_membership() to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'restaurants'
  ) then
    alter publication supabase_realtime add table public.restaurants;
  end if;
end $$;
